//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.OpenAI.Azure.CMSResources.Kentico.Xperience.OpenAI.Azure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kentico.Xperience.OpenAI.Azure.CMSResources.Kentico.Xperience.OpenAI.Azure.Resour" +
                            "ce", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure OpenAI.
        /// </summary>
        internal static string settingscategory_xperienceazureopenai {
            get {
                return ResourceManager.GetString("settingscategory.xperienceazureopenai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content categorization.
        /// </summary>
        internal static string settingscategory_xperienceazureopenai_contentcategorization {
            get {
                return ResourceManager.GetString("settingscategory.xperienceazureopenai.contentcategorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string settingscategory_xperienceazureopenai_general {
            get {
                return ResourceManager.GetString("settingscategory.xperienceazureopenai.general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure OpenAI API endpoint.
        /// </summary>
        internal static string settingskey_xperienceazureopenai_apiendpoint {
            get {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.apiendpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint of the Microsoft Azure OpenAI API resource. You can find the endpoint in the Microsoft Azure portal when viewing your Azure OpenAI resource..
        /// </summary>
        internal static string settingskey_xperienceazureopenai_apiendpoint_description {
            get {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.apiendpoint.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure OpenAI API key.
        /// </summary>
        internal static string settingskey_xperienceazureopenai_apikey {
            get {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid key of the Microsoft Azure OpenAI API resource specified by the endpoint setting. You can manage API keys in the Microsoft Azure portal when viewing your Azure OpenAI resource..
        /// </summary>
        internal static string settingskey_xperienceazureopenai_apikey_description {
            get {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.apikey.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Azure OpenAI Deployment name.
        /// </summary>
        internal static string settingskey_xperienceazureopenai_deploymentname {
            get
            {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.deploymentname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The deployment name of your Azure OpenAI API resource. You can find the deployment name in the Azure Open AI Studio under the Management -&gt; Deployments tab..
        /// </summary>
        internal static string settingskey_xperienceazureopenai_deploymentname_description {
            get
            {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.deploymentname.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable content categorization.
        /// </summary>
        internal static string settingskey_xperienceazureopenai_enablecontentcategorization {
            get {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.enablecontentcategorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables content categorization. The content categorization is performed by Microsoft Azure OpenAI..
        /// </summary>
        internal static string settingskey_xperienceazureopenai_enablecontentcategorization_description {
            get {
                return ResourceManager.GetString("settingskey.xperienceazureopenai.enablecontentcategorization.description", resourceCulture);
            }
        }
    }
}
